// ************************************************************************
// This file implements library imports for the caller.
// -------
// WARNING
// -------
// This file was generated by PWIG. Do not edit.
// File generated on 4.1.2017 17:40:15

#ifndef TESTLIB_CALLER_H
#define TESTLIB_CALLER_H

// Library properties:
// Name: TestLib
// Version: 1.0
// GUID: F3C093C0-035B-4C33-BB28-C1FDE270D3B5
// Description: Test library

#include <string>
#include "stdafx.h"
#include "stdint.h"
#include "testlib_intf.h"

// Forward declarations:
class ProjectGroup;
class Project;

// Name: ProjectGroup
// GUID: 7C12BB43-A6AB-4A52-8B1D-EDD5D94B344B
// Description: ProjectGroup Object

class ProjectGroup : public BaseTestLib
{
  private:
    IProjectGroup m_ItemHandle;
  public:
    ProjectGroup(IProjectGroup AInterfaceHandle = 0);
    ~ProjectGroup();
    // Methods:
    IProject AddProject();
    void RunPeriodic();
    void Finalize();
    // Property getters and setters:
    // Properties:
    // Events:
    virtual void CallEventOnError(TErrorCode ErrorCode, std::wstring ErrorText);
    virtual void CallEventOnProgress(TProgressEvent EventCode, int32_t ProgressValue, std::wstring EventText);
    // Default interface handle:
    IProjectGroup __GetHandle(void);
    __declspec( property (get=__GetHandle)) IProjectGroup Handle;
};

// Name: Project
// GUID: D96EA22B-D750-4C05-9F32-8C5C8E9F846D
// Description: Project Object

class Project : public BaseTestLib
{
  private:
    IProject m_ItemHandle;
  public:
    Project(IProject AInterfaceHandle = 0);
    ~Project();
    // Methods:
    void Connect();
    void Disconnect();
    TBool LoadFromFile(std::wstring Path);
    TBool SaveToFile(std::wstring Path);
    // Property getters and setters:
    int32_t GetConnectionFRC();
    std::wstring GetConnectionString();
    // Properties:
    __declspec( property (get=GetConnectionFRC)) int32_t ConnectionFRC;
    __declspec( property (get=GetConnectionString)) std::wstring ConnectionString;
    // Default interface handle:
    IProject __GetHandle(void);
    __declspec( property (get=__GetHandle)) IProject Handle;
};

bool TestLibLibLoad(std::wstring FileName);
void TestLibLibUnload();

#endif TESTLIB_CALLER_H

