// ************************************************************************
// This file contains common interface for both the caller and the callee.
// -------
// WARNING
// -------
// This file was generated by PWIG. Do not edit.
// File generated on 4.1.2017 17:40:15

// Library properties:
// Name: TestLib
// Version: 1.0
// GUID: F3C093C0-035B-4C33-BB28-C1FDE270D3B5
// Description: Test library


namespace TestLib
{

  // Enumerated types:

  // Enumerated type properties:
  // Name: TRetCode
  // GUID: 810C7D96-27EE-44A8-BA21-5161FF01BFA0
  // Description: Library return code

  public enum TRetCode {
    rcOk = 0,
    rcError = 1
  };

  // Enumerated type properties:
  // Name: TErrorCode
  // GUID: 6B90024F-AE26-42D4-8F6A-8BDA2EE69EF1
  // Description: Log message code

  public enum TErrorCode {
    errError = 0,
    errWarning = 1,
    errNote = 2,
    errHint = 3
  };

  // Enumerated type properties:
  // Name: TProgressEvent
  // GUID: 19B84FC3-1B2C-4E0C-A9F1-4B35EEA625BA
  // Description: Progress event code

  public enum TProgressEvent {
    peStart = 0,
    peAdvance = 1,
    peStop = 2
  };

  // Enumerated type properties:
  // Name: TBool
  // GUID: 6C87BDB8-1CE8-40DE-92CF-41C853A63453
  // Description: Library return code

  public enum TBool {
    bFalse = 0,
    bTrue = 1
  };

  public static class Global
  {
    public const string cLibGUID = "F3C093C0-035B-4C33-BB28-C1FDE270D3B5";

  }
}
